apiVersion: v1
kind: Template
metadata:
  name: maven-tomcat-pipeline
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}-platform
    name: ${APP_NAME}-platform
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: webserver31-tomcat8
  spec:
    tags:
    - annotations:
        supports: tomcat:8.x,java
        tags: builder,tomcat,java
        version: "3.1"
      from:
        kind: DockerImage
        name: registry.access.redhat.com/jboss-webserver-3/webserver31-tomcat8-openshift
      name: "3.1"
    - annotations:
        supports: java
        tags: builder,tomcat,java
      from:
        kind: ImageStreamTag
        name: "3.1"
      name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "${NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
    creationTimestamp: null
    labels:
      name: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          try {
             timeout(time: 20, unit: 'MINUTES') {
                def appName="${APP_NAME}"
                def project=""

                node {
                  stage("Initialize") {
                    project = env.PROJECT_NAME
                  }
                }

                node {
                  stage("Build Platform Image") {
                    sh "oc start-build ${appName}-platform -n ${project}"
                    openshiftVerifyBuild bldCfg: "${appName}-platform", namespace: project, waitTime: '20', waitUnit: 'min'
                  }
                }

                node("maven") {
                  stage("Checkout") {
                    git url: "${GIT_SOURCE_URL}", branch: "${GIT_SOURCE_REF}"
                  }

                  stage("Build WAR") {
                    sh "mvn clean package -Popenshift"
                    dir('target') {
                      stash name:"war", includes:"${ARTIFACT_NAME}.war"
                    }
                  }
                }

                node {
                  stage("Build Final Image") {
                    unstash name:"war"
                    sh "oc start-build ${appName}-docker --from-file=${ARTIFACT_NAME}.war -n ${project}"
                    openshiftVerifyBuild bldCfg: "${appName}-docker", namespace: project, waitTime: '20', waitUnit: 'min'
                  }

                  stage("Deploy") {
                    openshiftDeploy deploymentConfig: appName, namespace: project
                  }
                }
             }
          } catch (err) {
             echo "in catch block"
             echo "Caught: ${err}"
             currentBuild.result = 'FAILURE'
             throw err
          }
      type: JenkinsPipeline
    triggers:
    - github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
      type: GitHub
    - generic:
        secret: "${GENERIC_WEBHOOK_SECRET}"
      type: Generic
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}-platform
    name: ${APP_NAME}-platform
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}-platform:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: Git
      contextDir: src/main/docker
      git:
        uri: ${GIT_SOURCE_URL}
        ref: ${GIT_SOURCE_REF}
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: webserver31-tomcat8:latest
      type: Docker
    triggers: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}-docker
    name: ${APP_NAME}-docker
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      dockerfile: |-
        FROM ${APP_NAME}-platform
        COPY ${ARTIFACT_NAME}.war /opt/webserver/webapps/ROOT.war
        CMD /opt/webserver/bin/launch.sh
      binary:
        asFile: ROOT.war
      type: Docker
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}-platform:latest
      type: Docker
    triggers: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - image: ${APP_NAME}:latest
          imagePullPolicy: Always
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: DB_SERVICE_PREFIX_MAPPING
            value: ${APP_NAME}-postgresql=${BACKEND_DB_NAME}
          - name: ${BACKEND_DB_NAME}_JNDI
            value: 'jdbc/DocumentDS'
          - name: ${BACKEND_DB_NAME}_USERNAME
            valueFrom:
              secretKeyRef:
                key: postgresql-user
                name: ${BACKEND_DB_SECRET}
          - name: ${BACKEND_DB_NAME}_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresql-password
                name: ${BACKEND_DB_SECRET}
          - name: ${BACKEND_DB_NAME}_DATABASE
            value: ${BACKEND_DB_NAME}
          - name: ${APP_NAME_UPPER}_POSTGRESQL_SERVICE_HOST
            value: ${BACKEND_DB_SERVICE}
          - name: ${APP_NAME_UPPER}_POSTGRESQL_SERVICE_PORT
            value: '5432'
          - name: ${BACKEND_DB_NAME}_MAX_ACTIVE
            value: '250'
          - name: ${BACKEND_DB_NAME}_MAX_IDLE
            value: '20'
          - name: ${BACKEND_DB_NAME}_MAX_WAIT
            value: '30000'
          resources: {}
          terminationMessagePath: /dev/termination-log
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None
parameters:
- name: APP_NAME
  description: The name assigned to all of the application objects defined in this template, must be lowercase, no special characters.
  displayName: Application Name
  required: true
  value: jdbcquery
- name: APP_NAME_UPPER
  descrption: The name upercase version of APP_NAME, must be the exact uppercase of Application Name
  value: JDBCQUERY
- name: ARTIFACT_NAME
  description: The name of the artifact file to copy.
  displayName: Artifact Name
  required: true
  value: jdbc-query
- name: BACKEND_DB_SERVICE
  description: Service name for backend database
  required: true
  value: jdbcquery-data
- description: Backend database name, also used to create service name.
  name: BACKEND_DB_NAME
  required: true
  value: jdbcquery
- description: Backend DB Secret
  name: BACKEND_DB_SECRET
  required: true
  value: jdbcquery-dbname-secret
- description: path to backup data to retore from
  name: BACKEND_RESTORE_PATH
  value: minimal-2017-05-12-17-35-04
- name: GIT_SOURCE_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
  value: https://github.com/morbrian/sandbox-jdbc-query.git
- name: GIT_SOURCE_REF
  description: The source Ref for the application
  displayName: Source Ref
  required: true
  value: master
- description: Github trigger secret.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
  required: true
- description: A secret string used to configure the Generic webhook.
  displayName: Generic Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GENERIC_WEBHOOK_SECRET
  required: true
